Repository abhinavsrivas7/KARUSC-Dev, pull requests merged in 2024-01, with the labels that each got.

#55 Added .env file in client
  karusc.client/.env
  karusc.client/src/pages/Shop.tsx
  karusc.client/src/utilities/EndpointUtils.ts
Labels: enhancement

#56 Enhancement/dev53 add efcore
  .github/workflows/cd.yaml
  .gitignore
  Karusc.Server.Application/Contracts/IKaruscDbContext.cs
  Karusc.Server.Application/Karusc.Server.Application.csproj
  Karusc.Server.Application/Products/GetAllProducts/GetAllProductsRequestHandler.cs
  Karusc.Server.Infrastructure/InfrastructureStartup.cs
  Karusc.Server.Infrastructure/Karusc.Server.Infrastructure.csproj
  Karusc.Server.Infrastructure/Persistence/KaruscDbContext.cs
  Karusc.Server/Karusc.Server.csproj
  Karusc.Server/Program.cs
  Karusc.Server/appsettings.Production.json
  Karusc.Server/appsettings.json
  README.md
  karusc.client/README.md
Labels: enhancement

#57 updated dotnet ef version in pipeline
  .github/workflows/cd.yaml
Labels: enhancement

#58 updated environment variable using env keyword
  .github/workflows/cd.yaml
Labels: enhancement

#59 updated cd pipeline
  .github/workflows/cd.yaml
Labels: enhancement

#60 Enhancement/dev53 add efcore
  .github/workflows/cd.yaml
Labels: enhancement

#61 Enhancement/dev53 add efcore
  DigiCertGlobalRootCA.crt.pem
Labels: enhancement

#62 Enhancement/dev53 add efcore
  Karusc.Server/DigiCertGlobalRootCA.crt.pem
Labels: enhancement

#63 Enhancement/dev53 add efcore
  .github/workflows/cd.yaml
Labels: enhancement

#74 Enhancement/dev53 add efcore
  Karusc.Server/Karusc.Server.csproj
Labels: task

#75 added migration - addedProduct
  Karusc.Server.Infrastructure/Migrations/20240106055935_AddedProduct.Designer.cs
  Karusc.Server.Infrastructure/Migrations/20240106055935_AddedProduct.cs
  Karusc.Server.Infrastructure/Migrations/KaruscDbContextModelSnapshot.cs
Labels: task

#76 Enhancement/dev53 add efcore
  .gitignore
  add-ip.ps1
Labels: task

#80 ui revamp and font usage
  karusc.client/index.html
  karusc.client/karusc-styles.css
  karusc.client/src/App.tsx
  karusc.client/src/components/Authentication/GoogleAuthComponent.tsx
  karusc.client/src/components/Common/Footer.tsx
  karusc.client/src/components/Common/Loader.tsx
  karusc.client/src/components/Common/Navbar.tsx
  karusc.client/src/components/Common/NoData.tsx
  karusc.client/src/components/Common/SearchBar.tsx
  karusc.client/src/components/Products/ProductCard.tsx
  karusc.client/src/pages/Home.tsx
  karusc.client/src/pages/Shop.tsx
Labels: story

#83 fixed bugs
  karusc.client/src/App.tsx
  karusc.client/src/components/Common/Banner.tsx
  karusc.client/src/components/Common/Footer.tsx
  karusc.client/src/components/Common/Navbar.tsx
  karusc.client/src/components/Home/Banner.tsx
Labels: bug

#84 updated banner
  karusc.client/package.json
  karusc.client/src/App.tsx
  karusc.client/src/components/Home/Banner.tsx
Labels: bug

#85 Story/dev79 UI revamp
  karusc.client/src/App.tsx
  karusc.client/src/components/Home/DefaultCarousel.tsx
  karusc.client/src/components/Home/ShopByCard.tsx
Labels: story

#86 made carousel responsive and added more things to footer
  karusc.client/index.html
  karusc.client/karusc-styles.css
  karusc.client/resources/media/carousel.svg
  karusc.client/resources/media/carousel1.jpg
  karusc.client/resources/media/carousel2.jpg
  karusc.client/resources/media/carousel3.jpg
  karusc.client/resources/media/facebook.svg
  karusc.client/resources/media/instagram.svg
  karusc.client/resources/media/pinterest.svg
  karusc.client/resources/media/youtube.svg
  karusc.client/src/App.tsx
  karusc.client/src/components/Common/Footer.tsx
  karusc.client/src/components/Home/DefaultCarousel.tsx
  karusc.client/src/components/Home/ShopBy.tsx
  karusc.client/src/components/Home/ShopByCard.tsx
Labels: story

#88 Story/dev79 UI revamp
  karusc.client/src/components/Common/Footer.tsx
Labels: story

#90 Screen Size context
  karusc.client/resources/media/hamburg.svg
  karusc.client/src/App.tsx
  karusc.client/src/components/Common/Navbar.tsx
  karusc.client/src/context/ScreenSizeContext.tsx
  karusc.client/src/context/ViewportContext.ts
Labels: task

#91 added reviews section
  karusc.client/karusc-styles.css
  karusc.client/package.json
  karusc.client/resources/media/user-profile-photo.jpg
  karusc.client/src/components/Home/Review.tsx
  karusc.client/src/components/Home/ReviewCard.tsx
  karusc.client/src/components/Home/ShopBy.tsx
  karusc.client/src/pages/Home.tsx
Labels: story

#92 made corrections for tablet
  karusc.client/src/components/Common/Navbar.tsx
  karusc.client/src/components/Home/Review.tsx
  karusc.client/src/components/Home/ReviewCard.tsx
  karusc.client/src/components/Home/ShopBy.tsx
  karusc.client/src/context/ScreenSizeContext.tsx
  karusc.client/src/models/DeviceTypes.ts
Labels: story

#93 Story/dev79 UI revamp
  karusc.client/src/components/Home/ShopBy.tsx
Labels: story

#94 Story/dev79 UI revamp
  karusc.client/src/components/Home/Review.tsx
Labels: story

#95 Story/dev79 UI revamp
  karusc.client/src/components/Common/Footer.tsx
  karusc.client/src/components/Home/Review.tsx
  karusc.client/src/components/Home/ReviewCard.tsx
Labels: story

#96 Story/dev79 UI revamp
  karusc.client/karusc-styles.css
Labels: story

#97 Story/dev79 UI revamp
  karusc.client/index.html
  karusc.client/karusc-styles.css
  karusc.client/package.json
  karusc.client/src/App.tsx
  karusc.client/src/main.tsx
Labels: story

#98 Story/dev79 UI revamp
  karusc.client/index.html
  karusc.client/karusc-styles.css
  karusc.client/package.json
  karusc.client/resources/media/backArrow.svg
  karusc.client/resources/media/cart.svg
  karusc.client/resources/media/facebook.svg
  karusc.client/resources/media/hamburg.svg
  karusc.client/resources/media/hamburger.svg
  karusc.client/resources/media/instagram.svg
  karusc.client/resources/media/pinterest.svg
  karusc.client/resources/media/search.svg
  karusc.client/resources/media/user.svg
  karusc.client/resources/media/youtube.svg
  karusc.client/src/App.tsx
  karusc.client/src/components/Common/Navbar.tsx
  karusc.client/src/components/Home/Review.tsx
  karusc.client/src/components/Home/ShopByCard.tsx
  karusc.client/src/main.tsx
  karusc.client/src/pages/Home.tsx
Labels: story

#99 fixed padding bug
  karusc.client/src/components/Common/Navbar.tsx
  karusc.client/src/components/Common/SearchBar.tsx
Labels: story

#105 Story/dev102 configure file storage
  Karusc.Server.Application/Products/Delete/DeleteProductCommand.cs
  Karusc.Server.Application/Products/Delete/DeleteProductCommandHandler.cs
  Karusc.Server/Controllers/ProductController.cs
  karusc.client/src/components/Products/ProductCard.tsx
  karusc.client/src/models/Product.ts
Labels: story

#106 Story/dev102 configure file storage
  Karusc.Server.Application/Products/Delete/DeleteProductCommandHandler.cs
  karusc.client/karusc-styles.css
  karusc.client/src/App.tsx
  karusc.client/src/components/Admin/Products/AddProduct.tsx
  karusc.client/src/components/Admin/Products/ProductOperations.tsx
  karusc.client/src/components/Common/Navbar.tsx
  karusc.client/src/pages/Admin.tsx
Labels: story

#109 Story/dev107 admin panel
  Karusc.Server.Infrastructure/FileStorage/BunnyFileStorageService.cs
  karusc.client/src/components/Admin/Collections/UpdateCollection.tsx
Labels: bug
